version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin-compose:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "gusta@api.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "54321:80"
    depends_on:
      - postgres
